image: docker.slock.it/build-images/node:8-alpine

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

build-in3:
  stage: build
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
  artifacts:
    paths:
      - js/

test-in3:
  stage: test
  script:
    - npm test
  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report