image: node:8-alpine

stages:
  - build

build-in3:
  stage: build
  script:
    - apk add --no-cache python make gcc g++ git openssh
    - npm install
    - npm run build
  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report
