image: node:8-alpine

stages:
  - build
  - test
  - deploy

build-in3:
  stage: build
  script:
    - apk add --no-cache python make gcc g++ git openssh
    - echo "//npm.slock.it/:_authToken=\"ufUzrNWjrIdX7nn+WZQzV7ZLyJwrMBX2ynTbm+5R8TE=\"" > ~/.npmrc
    - npm set registry https://npm.slock.it
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - js/
      - ~/.npmrc

test-in3:
  stage: test
  script:
    - npm test
  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report

deploy-to-slockit-npm:
  stage: deploy
  only: tags
  dependencies:
    - build-in3
  script:
    - npm version $CI_COMMIT_TAG
    - npm publish
