sudo: required

dist: trusty

language: node_js

node_js:
  - "8.3.0"

before_install:
  - docker pull parity/parity:v1.7.0
  - docker run -dti --network="host" -p 8180:8180 -p 8545:8545 -p 30303:30303 -p 8546:8546 parity/parity:v1.7.0 --chain dev
  - while ! echo exit | nc localhost 8546; do sleep 1; done
  
install:
  - npm install
  - npm run build

services:
  - docker

after_script:
        - scp -i ~/.ssh/travis -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r test/report/* "travis@46.38.250.122:in3-ts/" 

notifications:
  slack:
      rooms:
         - slockitteam:HARkL0L8gSaKg55PNEKFoUWW#prv_code

