sudo: required

dist: trusty

language: node_js

node_js:
  - "8.3.0"

install:
  - npm install
  - npm run build

after_script:
        - scp -i ~/.ssh/travis -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r test/report/* "travis@46.38.250.122:in3/" 

notifications:
  slack:
      rooms:
         - slockitteam:HARkL0L8gSaKg55PNEKFoUWW#prv_code

