$schema: http://json-schema.org/schema#
description: configuration-data, which represents the structure of the config-file.
definitions: 

    IN3NodeWeight: 
        description: a local weight of a n3-node.
        type: object
        properties:
            weight:
                description: factor the weight this noe (default 1.0)
                type: number
            responseCount:
                description: number of uses.
                type: integer
            avgResponseTime:
                description: average time of a response
                type: number
            pricePerRequest:
                description: last price
                type: integer
            lastRequest:
                description: timestamp of the last request in ms
                type: integer
            blacklistedUntil: 
                description: blacklisted because of failed requests until the timestamp
                type: integer

    IN3NodeConfig: 
        description: a config of a n3-node.
        type: object
        required: [ address,url,deposit, chainIds]
        properties:
            address:
                description: the address of the node, which is the public address it iis signing with.
                type: string
            url:
                description: the endpoint to post to
                type: string
            chainIds:
                description: the list of supported chains
                type: array
                items:
                    type: string
                    pattern: ^0x[0-9a-fA-F]+$
            deposit:
                description: the deposit of the node
                type: integer


    IN3RPCRequestConfig:
        description: additional config for a IN§ RPC-Request
        properties:
            chainId: 
                description: the requested chainId
                type: string
            includeCode: 
                description: if true, the request should include the codes of all accounts. otherwise only the the codeHash is returned. In this case the client may ask by calling eth_getCode() afterwards
                type: boolean
            verification: 
                description: defines the kind of proof the client is asking for
                type: string
                enum: [ never, proof, proofWithSignature ]
            signatures: 
                description: a list of addresses requested to sign the blockhash
                type: array
                items:
                    type: string
                    pattern: ^0x[0-9a-fA-F]+$

    Signature:
        type: object
        properties:
            address:
                type: string
                description: the address of the signing node
            block:
                type: number
                description: the blocknumber
            blockHash:
                type: string
                description: the hash of the block
            msgHash:
                type: string
                description: hash of the message
                format: bytes32
            r: 
                type: string
                description: Positive non-zero Integer signature.r
                format: hex
            s: 
                type: string
                description: Positive non-zero Integer signature.s
                format: hex
            v: 
                type: string
                description: Calculated curve point, or identity element O.
                format: hex
            
    IN3ResponseConfig:
        type: object
        description: additional config for a IN§ RPC-Request
        properties:
            proof:
                type: object
                additionalProperties: 
                    type:  [ array, object, string, number]
            lastNodeList: 
                description: the blocknumber for the last block updating the nodelist
                type: number
            signatures: 
                description: a list of addresses requested to sign the blockhash
                type: array
                items:
                    $ref: "#/definitions/Signature"

    IN3Config:
        description: the definition of the config-file.
        type: object
        required: [ minDeposit, requestCount, chainId]
        properties:
            contract:
                type: string
                description: the address of the registry contract
            minDeposit:
                type: number
                description: min stake of the server. Only nodes owning at least this amount will be chosen.
            requestCount:
                type: number
                min: 1
                default: 1
                description: the number of request send when getting a first answer
            timeout:
                type: number
                min: 1
                default: 1
                description: specifies the number of milliseconds before the request times out.
            chainId:
                type: string
                pattern: ^0x[0-9a-fA-F]+$
                description: servers to filter for the given chain. The chain-id based on EIP-155.
            nodeList:
                description: the list of nodes
                type: array
                items:
                    $ref: "#/definitions/IN3NodeConfig"
            nodeAuthorities:
                description: the list of authority nodes for handling conflicts
                type: array
                items:
                    type: string
            weights:
                description: the weights of nodes depending on former performance
                type: object
                additionalProperties: 
                    $ref: "#/definitions/IN3NodeWeight"

    RPCRequest:
        type: object
        description: a JSONRPC-Request with N3-Extension
        required: [jsonrpc, method]
        properties:
            jsonrpc: 
                description: the version
                type: string
                enum: ["2.0"]
            method: 
                description: the method to call
                type: string
            id: 
                description: the id
                type: [string, number]
            params: 
                description: the params
                type: [ array, object]
            in3: 
                description: the IN3-Config 
                $ref: "#/definitions/IN3RPCRequestConfig"

    RPCResponse:
        type: object
        description: a JSONRPC-Responset with N3-Extension
        required: [jsonrpc, id]
        properties:
            jsonrpc: 
                description: the version
                type: string
                enum: ["2.0"]
            id: 
                description: the id matching the request
                type: [string, number]
            error: 
                description: in case of an error this needs to be set
                type: string
            result: 
                description: the params
                type: [ array, object, string, number]
                additionalProperties: 
                    type:  [ array, object, string, number]
            in3: 
                description: the IN3-Result
                $ref: "#/definitions/IN3ResponseConfig"

            in3Node:
                description: the node handling this response (internal only)
                $ref: "#/definitions/IN3NodeConfig"

